# Generated by Django 4.1.4 on 2023-02-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_14', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedb',
            name='recipe_image',
            field=models.ImageField(upload_to='Recipedb'),
        ),
    ]
