# Generated by Django 4.1.4 on 2023-02-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_14', '0002_alter_recipedb_recipe_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipedb',
            new_name='Sample',
        ),
    ]
