# Generated by Django 4.1.4 on 2023-02-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_14', '0003_rename_recipedb_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='recipe_image',
            field=models.ImageField(upload_to='Sample'),
        ),
    ]
