# Generated by Django 4.1.4 on 2023-02-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_14', '0004_alter_sample_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('subject', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
