# Generated by Django 4.1.4 on 2023-02-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_14b', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Simple',
        ),
    ]
