# Generated by Django 4.1.4 on 2023-02-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_14b', '0002_delete_simple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=15)),
                ('phone', models.TextField(max_length=12)),
            ],
        ),
    ]
